<a href="https://colab.research.google.com/github/Maram00ali/REV4RE/blob/main/Basic_classification_SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv('dataset path')
dataset.head()

Review  RivewRelevance
0                                    5 star good app               1
1                A monthly subscription fee. Really?               1
2  Able to customize and decorate a ton of things...               1
3           All I can say is this game is the best!!               1
4  Although not the best, it better for own creat...               1

In [ ]:
len(dataset)

84932

In [ ]:
dataset.isnull().sum()

Review            0
RivewRelevance    0
dtype: int64

In [ ]:
# calculate count of each category
labels, counts = np.unique(dataset.RivewRelevance, return_counts=True)
# convert data.target_names to np array for fancy indexing

print(dict(zip(labels, counts)))


{0: 10352, 1: 69045, 2: 5535}


# Split dataset

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(dataset.Review, dataset.RivewRelevance)
list(t[:80] for t in X_train[:10])

['So I’ve made many CapCut edits for my friends. However today everything was stra',
 'I have a problem with downloading videos\n, so I deleted the app and reinstall it',
 "Haven't had a chance to read a book",
 'New layout is terrible. Deleted it.',
 'Support service is too bad..',
 'I haven’t tried it yet so I’m going to give it a one star',
 'This game so fun!!!',
 'Just all out fun to play',
 'I redid my home screen like 26 times and this has been the best app to make it l',
 'I was trying to change my age since I accidentally pressed the wrong age and I a']

# Prepare dataset

In [ ]:
#dataset pre_processing

In [ ]:
# Extracting features from text files (pure extraction)
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(X_train)
X_train_counts.shape

(63699, 30935)

In [ ]:
#TF_IDF feauture extraction
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(stop_words="english", max_features=1000, decode_error="ignore")
vectorizer.fit(X_train)


TfidfVectorizer(decode_error='ignore', max_features=1000, stop_words='english')

# start with the basic classification

In [ ]:
# import library
import re
import nltk
from bs4 import BeautifulSoup
import spacy
from sklearn.svm import SVC
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import Normalizer
from sklearn import preprocessing
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, accuracy_score
from sklearn import metrics



/shared-libs/python3.9/py/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2023-03-28 15:56:57.673414: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-28 15:56:57.793340: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-03-28 15:56:57.797726: W tensorflow/stream_executor/platform/default/dso_loader.

# SVM

In [ ]:
# Stemming Code

import nltk
nltk.download()

from nltk.stem.snowball import SnowballStemmer
stemmer = SnowballStemmer("english", ignore_stopwords=True)

class StemmedCountVectorizer(CountVectorizer):
    def build_analyzer(self):
        analyzer = super(StemmedCountVectorizer, self).build_analyzer()
        return lambda doc: ([stemmer.stem(w) for w in analyzer(doc)])

NLTK Downloader
---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------


KeyboardInterrupt: Interrupted by user

In [ ]:
#pure extraction without any processing
#svc_l = Pipeline([
 #       ("count_vectorizer", CountVectorizer(max_features=None)),
 #       ("linear svc", SVC(kernel="linear"))
 #   ])

In [ ]:
#pure extraction without any processing
#svc_rbf = Pipeline([
   #     ("count_vectorizer", CountVectorizer(max_features=None)),
    #    ("rbf svc", SVC(kernel='rbf', gamma=0.5, C=0.1))
    #])

In [ ]:
#pure extraction without any processing
#svc_poly = Pipeline([
#        ("count_vectorizer", CountVectorizer(max_features=None)),
#        ("polt svc", SVC(kernel='poly', degree=3, C=1))
#    ])


In [ ]:
#pure extraction with stopword removal  (best of the three kernals)
svc = Pipeline([
        ("count_vectorizer", CountVectorizer(stop_words="english",max_features=None)),
        ("linear svc", SVC(kernel="linear"))
    ])

In [ ]:
#TF_IDF extraction with stopword removal  (TF_IDF)without stopword
svc = Pipeline([
        ("TF_IDF_vectorizer", TfidfVectorizer(stop_words="english", max_features=None)),
        ("linear svc", SVC(kernel="linear"))
    ])

In [ ]:
#normlizing text
import numpy as np
from sklearn import preprocessing

norm_dataset = preprocessing.normalize(dataset.Review)
scaled_df = pd.DataFrame(norm_dataset, columns=dataset.data.columns)
print(scaled_df)

ValueError: could not convert string to float: '5 star good app'

In [ ]:
#TF_IDF extraction with stopword removal + normalization

stemmed_count_vect = StemmedCountVectorizer(stop_words='english')
from sklearn.preprocessing import Normalizer

svc = Pipeline([("TF_IDF_vectorizer",stemmed_count_vect),('norm', Normalizer()),
        ("linear svc", SVC(kernel="linear")) ])

In [ ]:
#svc = Pipeline([
#        ("count_vectorizer", CountVectorizer(stop_words="english", max_features=3000)),
#        ("linear svc", SVC(kernel="linear"))
#    ])
#svc_tfidf = Pipeline([
#        ("tfidf_vectorizer", TfidfVectorizer(stop_words="english", max_features=3000)),
#        ("linear svc", SVC(kernel="linear"))
#    ])

In [ ]:
#steemmed count vec + normalization

model = svc
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.8616304808552725
              precision    recall  f1-score   support

           0       0.74      0.51      0.60      2579
           1       0.87      0.98      0.92     17273
           2       0.54      0.02      0.05      1381

    accuracy                           0.86     21233
   macro avg       0.72      0.50      0.52     21233
weighted avg       0.84      0.86      0.83     21233



In [ ]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[ 1309  1253    17]
 [  309 16952    12]
 [  154  1193    34]]


In [ ]:
print(model.predict(['Would like to use dark mode, but I’m on iOS 12. Hope soon you will be able to enable dark theme via WhatsApp settings and not the phone settings 😎']))

[1]


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=378be7ce-053e-4e53-a8d7-d43f011c835b' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>