<a href="https://colab.research.google.com/github/Maram00ali/REV4RE/blob/main/Basic_classification_LR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv('dataset path')
dataset.head()

Review  RivewRelevance
0                                    5 star good app               1
1                A monthly subscription fee. Really?               1
2  Able to customize and decorate a ton of things...               1
3           All I can say is this game is the best!!               1
4  Although not the best, it better for own creat...               1

In [ ]:
len(dataset)

84932

In [ ]:
dataset.isnull().sum()

Review            0
RivewRelevance    0
dtype: int64

In [ ]:
# calculate count of each category
labels, counts = np.unique(dataset.RivewRelevance, return_counts=True)
# convert data.target_names to np array for fancy indexing

print(dict(zip(labels, counts)))


{0: 10352, 1: 69045, 2: 5535}


# Split dataset

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(dataset.Review, dataset.RivewRelevance)
list(t[:80] for t in X_train[:10])

['AliExpress is good store',
 "please add status update like what's app! please",
 'They should call this scamscanner. I needed an app that would scan legal documen',
 'I have been using this Web site for a couple of years and I only had two discrep',
 'All good but pls add story at telegram',
 'i like the dictionary and word marking feature most. Preferably using this app f',
 'Great and dependable. It works!',
 "I can't access my account yet it's not been disabled, keeps saying can't load fe",
 'AliExpress has better deals than eBay. Shipping takes a little longer but it’s w',
 'My app was updated to the latest version yesterday (Version 7.8.1), and it doesn']

# Prepare dataset

In [ ]:
#dataset pre_processing

In [ ]:
# Extracting features from text files (pure extraction)
#from sklearn.feature_extraction.text import CountVectorizer
#count_vect = CountVectorizer()
#X_train_counts = count_vect.fit_transform(X_train)
#X_train_counts.shape

(63699, 30723)

In [ ]:
#TF_IDF feauture extraction
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(stop_words="english", max_features=1000, decode_error="ignore")
vectorizer.fit(X_train)


TfidfVectorizer(decode_error='ignore', max_features=1000, stop_words='english')

# start with the basic classification

In [ ]:
# import library
import re
import nltk
from sklearn.svm import SVC
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import Normalizer
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, accuracy_score
from sklearn import metrics



#

In [ ]:
# Stemming Code

import nltk
nltk.download()

from nltk.stem.snowball import SnowballStemmer
stemmer = SnowballStemmer("english", ignore_stopwords=True)

class StemmedCountVectorizer(CountVectorizer):
    def build_analyzer(self):
        analyzer = super(StemmedCountVectorizer, self).build_analyzer()
        return lambda doc: ([stemmer.stem(w) for w in analyzer(doc)])

NLTK Downloader
---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------

Download which package (l=list; x=cancel)?
       | 
       | Downloading package abc to /root/nltk_data...
       |   Package abc is already up-to-date!
       | Downloading package alpino to /root/nltk_data...
       |   Package alpino is already up-to-date!
       | Downloading package averaged_perceptron_tagger to
       |     /root/nltk_data...
       |   Package averaged_perceptron_tagger is already up-to-date!
       | Downloading package averaged_perceptron_tagger_ru to
       |     /root/nltk_data...
       |   Package averaged_perceptron_tagger_ru is already up-to-
       |       date!
       | Downloading package basque_grammars to /root/nltk_data...
       |   Package basque_grammars is already up-to-date!
       | Downloading package bcp

In [ ]:
#normlizing text
#import numpy as np
#from sklearn import preprocessing

#norm_dataset = preprocessing.normalize(dataset.data)
#scaled_df = pd.DataFrame(norm_dataset, columns=dataset.data.columns)
#print(scaled_df)

                                                       0
0        (0, 2341)\t0.22941573387056174\n  (0, 3554)\...
1        (0, 157)\t0.1414213562373095\n  (0, 484)\t0....
2        (0, 1839)\t0.19245008972987526\n  (0, 2029)\...
3        (0, 1615)\t0.11785113019775793\n  (0, 2160)\...
4        (0, 1554)\t0.1386750490563073\n  (0, 2160)\t...
...                                                  ...
63694    (0, 2160)\t0.08980265101338746\n  (0, 3458)\...
63695    (0, 1398)\t0.2886751345948129\n  (0, 2140)\t...
63696    (0, 1261)\t0.35355339059327373\n  (0, 12097)...
63697    (0, 2513)\t0.5\n  (0, 10669)\t0.5\n  (0, 116...
63698    (0, 1839)\t0.1543033499620919\n  (0, 2160)\t...

[63699 rows x 1 columns]


# LR

In [ ]:
#LR pure extraction without processing
#LR = Pipeline([('vect', CountVectorizer(max_features=None)),
#                     ('clf',  LogisticRegression())])

In [ ]:
#LR pure extraction +stopword
#LR = Pipeline([('vect', CountVectorizer(stop_words='english')),
#                     ('clf',  LogisticRegression(solver='lbfgs', max_iter=1000))])

In [ ]:
#LR pure extraction without processing +TF_IDF transformer

LR = Pipeline([('vect', CountVectorizer(stop_words='english')), ('tfidf', TfidfTransformer()),
                     ('clf',  LogisticRegression(solver='lbfgs', max_iter=1000))])

In [ ]:
#LR TF_IDF without processing
#LR = Pipeline([('vect', TfidfVectorizer( max_features=None,decode_error="ignore")),
#                     ('clf', LogisticRegression(solver='lbfgs', max_iter=1000))])

In [ ]:
#LR TF_IDF +stop word
#TF_IDF feauter extraction wihout any processing
LR = Pipeline([('vect', TfidfVectorizer(stop_words='english', max_features=None,decode_error="ignore"),('tfidf', TfidfTransformer())),
                     ('clf',  LogisticRegression(solver='lbfgs', max_iter=1000))])

In [ ]:
#TF_IDF extraction with stopword +TF_IDF transformer
LR = Pipeline([('vect', TfidfVectorizer(stop_words='english',decode_error="ignore")),
                     ('clf',  LogisticRegression(solver='lbfgs', max_iter=1000))])

In [ ]:
#LR  + normalization
LR = Pipeline([('vect', CountVectorizer(max_features=None, stop_words='english')), ('norm', Normalizer()),
                    ('clf', LogisticRegression(solver='lbfgs', max_iter=1000))])

In [ ]:
#LR stopword +steeming
stemmed_count_vect = StemmedCountVectorizer(stop_words='english')

LR = Pipeline([('vect', stemmed_count_vect),
                    ('clf', LogisticRegression(solver='lbfgs', max_iter=1000))])

In [ ]:
#LR +stopword + stemmed +normalization
stemmed_count_vect = StemmedCountVectorizer(stop_words='english')
LR = Pipeline([('vect', stemmed_count_vect), ('norm', Normalizer()),
                    ('clf', LogisticRegression(solver='lbfgs', max_iter=1000))])

In [ ]:
#LR +stopword + stemmed +normalization
LR_model = LR
LR_model.fit(X_train, y_train)
y_pred = LR_model.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred ))

0.8605001648377526
              precision    recall  f1-score   support

           0       0.74      0.54      0.63      2590
           1       0.88      0.98      0.92     17179
           2       0.42      0.06      0.11      1464

    accuracy                           0.86     21233
   macro avg       0.68      0.53      0.55     21233
weighted avg       0.83      0.86      0.83     21233



In [ ]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred )
print(cm)

[[ 1396  1139    55]
 [  323 16782    74]
 [  157  1214    93]]


In [ ]:
print(LR_model.predict(['Would like to use dark mode, but I’m on iOS 12. Hope soon you will be able to enable dark theme via WhatsApp settings and not the phone settings 😎']))

[1]


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=378be7ce-053e-4e53-a8d7-d43f011c835b' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>